import './globals.css';
import { PropsWithChildren } from 'react';

export const metadata = {
  title: 'Clocks',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body className="flex h-screen items-center bg-neutral-900">
        {children}
      </body>
    </html>
  );
}
